# Generated by Django 4.2.1 on 2023-06-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idcategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='image/')),
                ('referencia', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('origen', models.CharField(max_length=30)),
                ('serie', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='index.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo_persona', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=24)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='index.genero')),
            ],
        ),
    ]
